[tool.ruff]

select = ["E", "F", "W", "B", "A001", "A002", "C4", "DTZ", "T10", "ISC", "PIE", "T20", "Q", "RSE", "RET", "SIM", "ERA",
          "PLR1711", "PLR5501", "PLR1714", "FLY", "RUF005", "RUF011"]
ignore = ["F405", "F403", "C408"]  # star imports
builtins = ["base", "loader", "messenger", "directNotify", "simbase", "taskMgr", "uber",
            "globalClock", "__dev__",
            "camera", "render", "hidden", "render2d", "aspect2d"]
extend-exclude = ["otp/distributed/DCClassImports.py", "toontown/ai/AIStart.py", "toontown/uberdog/UDStart.py",
                  "toontown/toonbase/ToontownStart.py", "toontown/toonbase/TTLocalizer.py"]
line-length = 120
target-version = "py39"
src = ["toontown", "otp"]
